name: Eleventy Build
on: 
  push:
    branches:
      - development  # Set a branch name to trigger deployment
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          install_dependencies: true
          publish_dir: docs-src
          destination_dir: docs
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}