name: Eleventy Build
on: 
  push:
    branches:
      - development  # Set a branch name to trigger deployment
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Run build
        run: npm run docs
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: master  # default: gh-pages
